experiment_dir: /space/hall7/sitestore/eccc/crd/cccma/users/rpg002/output/cccma_PPP_tests/test_4
max_epochs: 100
train_loader:
    dataset_config:
        model:
          paths: /space/hall7/sitestore/eccc/crd/cccma/users/rpg002/data/tas/forecast_data
          names: [tas]
          preprocessing_pipeline:
            preprocessors_list:
              - name: anomalies
                args:
                  dims: [year]
              # - name: flattener

          ensemble_mean : True
          concat_dim : year
          
        observation :
            paths: /space/hall7/sitestore/eccc/crd/cccma/users/rpg002/data/tas/observations/ERA5
            names: [tas]
            preprocessing_pipeline :
                    preprocessors_list :
                            - name : anomalies
                              args:
                                    dims: [year]
                            # - name : flattener

            concat_dim : year
            rename_dict :
                            lead_time : month

        condition_method : ensemble_mean
        lead_months : 
                      start: 1
                      end: 60

    batch_size: 10
    time_features :
                    - year
                    
    train_years : [1961, 2015]
    num_validation_years : 5
    prefetch_factor : 4
    num_data_workers: 4
    reduce_spatial_mask: True
    load: True

module:
    type :  cvae #deterministic
    config:
            # ModelConfig :
            #         type : MLP
            #         config :
            #               encoder_hidden_dims : [3000,3000,3000]
            #               latent_size : 10
            #               decoder_hidden_dims: [3000,3000,3000]
            #               condition_embedding_dims :  [3000,3000,3000]
            #               condition_embedding_size : 10
            #               condition_dependant_latent: False
            #               condemb_to_decoder:  True
            #               batch_normalization : True
            #               dropout_rate: 0.5
            #               init_method :  xavier

            ModelConfig :
                    type : UNet
                    config :
                        channels: [16,32,64,128,256]
                        block_config: 
                                name: convnext
                                num_blocks: 2
                        output_block_hidden_channels: 32
                        latent_size: 500
                        deterministic_guess_config:
                            load_dir: /space/hall7/sitestore/eccc/crd/cccma/users/rpg002/output/cccma_PPP_tests/test_3/checkpoints/best.pt
                            freeze_weights: True
                            share_output_block: True    
                        # GENERATOR: 
                        #         noise_level:  full
                        #         num_training_noise_samples: 10
                        

                    
losspipeline:
      loss_pipeline :
                    - name : mse

      reduction : mean

trainer :
    beta_finder :
              beta : 10
              num_epoch_to_warmup : 10
#     gradient_accumulation_steps: 2
    earlystoppingbuffer : 10

    mixed_precision: True              

optimization :
        lr : 0.0001
        optimizer_type : adam
        lr_scheduler_config :
                    min_lr : 0.00001
                    warmup_epochs : 2
                    total_epochs: 10
                    hold_min_lr: True

weights :
        spatial_method : uniform

log_every_n_epochs : 2
save_checkpoint : True
seed : 10

